// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type EmailVerificationToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type GameSession struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	GameMode        string
	TotalQuestions  int32
	CorrectAnswers  int32
	TotalScore      int32
	DurationSeconds int32
	TracksPlayed    []string
	CompletedAt     sql.NullTime
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type SpotifyToken struct {
	UserID       uuid.UUID
	RefreshToken string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	AccessToken  string
	TokenType    string
	Scope        string
	ExpiresAt    time.Time
}

type User struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
	EmailVerified  sql.NullBool
	DisplayName    string
	AvatarUrl      sql.NullString
	LastLoginAt    sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type UserSession struct {
	ID        string
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}
