// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type EmailVerificationToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type GameSession struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	GameMode        string
	TotalQuestions  int32
	CorrectAnswers  int32
	TotalScore      int32
	DurationSeconds int32
	TracksPlayed    []string
	CompletedAt     sql.NullTime
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type Playlist struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Name              string
	Description       sql.NullString
	SpotifyPlaylistID sql.NullString
	IsPublic          bool
	SyncWithSpotify   bool
	LastSyncedAt      sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type PlaylistSong struct {
	ID             uuid.UUID
	PlaylistID     uuid.UUID
	SpotifyTrackID string
	Position       int32
	TrackName      string
	ArtistName     string
	AlbumName      sql.NullString
	DurationMs     sql.NullInt32
	AddedAt        time.Time
}

type SpotifyAlbum struct {
	ID                   string
	Name                 string
	AlbumType            string
	ReleaseDate          sql.NullTime
	ReleaseDatePrecision sql.NullString
	TotalTracks          sql.NullInt32
	ImageUrl             sql.NullString
	Label                sql.NullString
	Popularity           sql.NullInt32
	CachedAt             time.Time
	UpdatedAt            time.Time
}

type SpotifyAlbumArtist struct {
	AlbumID  string
	ArtistID string
}

type SpotifyArtist struct {
	ID             string
	Name           string
	ImageUrl       sql.NullString
	Popularity     sql.NullInt32
	FollowersTotal sql.NullInt32
	Genres         []string
	CachedAt       time.Time
	UpdatedAt      time.Time
}

type SpotifyPlaylistsCache struct {
	ID               string
	Name             string
	Description      sql.NullString
	OwnerID          string
	OwnerDisplayName sql.NullString
	Public           sql.NullBool
	Collaborative    sql.NullBool
	FollowersTotal   sql.NullInt32
	TotalTracks      sql.NullInt32
	ImageUrl         sql.NullString
	CachedAt         time.Time
	UpdatedAt        time.Time
}

type SpotifyToken struct {
	UserID       uuid.UUID
	RefreshToken string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	AccessToken  string
	TokenType    string
	Scope        string
	ExpiresAt    time.Time
}

type SpotifyTrack struct {
	ID          string
	Name        string
	AlbumID     sql.NullString
	DurationMs  int32
	DiscNumber  sql.NullInt32
	TrackNumber sql.NullInt32
	Popularity  sql.NullInt32
	Explicit    sql.NullBool
	PreviewUrl  sql.NullString
	IsLocal     sql.NullBool
	CachedAt    time.Time
	UpdatedAt   time.Time
}

type SpotifyTrackArtist struct {
	TrackID   string
	ArtistID  string
	IsPrimary sql.NullBool
}

type User struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
	EmailVerified  sql.NullBool
	DisplayName    string
	AvatarUrl      sql.NullString
	LastLoginAt    sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type UserSession struct {
	ID        string
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}
