// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: playlists.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addSongToPlaylist = `-- name: AddSongToPlaylist :one
INSERT INTO local_playlist_tracks (playlist_id, spotify_track_id, position, updated_at)
VALUES ($1, $2, $3, NOW())
RETURNING playlist_id, spotify_track_id, position, updated_at
`

type AddSongToPlaylistParams struct {
	PlaylistID     uuid.UUID
	SpotifyTrackID string
	Position       int32
}

// Playlist songs operations
func (q *Queries) AddSongToPlaylist(ctx context.Context, arg AddSongToPlaylistParams) (LocalPlaylistTrack, error) {
	row := q.db.QueryRowContext(ctx, addSongToPlaylist, arg.PlaylistID, arg.SpotifyTrackID, arg.Position)
	var i LocalPlaylistTrack
	err := row.Scan(
		&i.PlaylistID,
		&i.SpotifyTrackID,
		&i.Position,
		&i.UpdatedAt,
	)
	return i, err
}

const bulkInsertPlaylistTracks = `-- name: BulkInsertPlaylistTracks :exec
INSERT INTO local_playlist_tracks (playlist_id, spotify_track_id, position, updated_at)
SELECT $1, unnest($2::text[]), unnest($3::int[]), NOW()
`

type BulkInsertPlaylistTracksParams struct {
	PlaylistID uuid.UUID
	Column2    []string
	Column3    []int32
}

func (q *Queries) BulkInsertPlaylistTracks(ctx context.Context, arg BulkInsertPlaylistTracksParams) error {
	_, err := q.db.ExecContext(ctx, bulkInsertPlaylistTracks, arg.PlaylistID, pq.Array(arg.Column2), pq.Array(arg.Column3))
	return err
}

const clearPlaylistSongs = `-- name: ClearPlaylistSongs :exec
DELETE FROM local_playlist_tracks WHERE playlist_id = $1
`

func (q *Queries) ClearPlaylistSongs(ctx context.Context, playlistID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearPlaylistSongs, playlistID)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM local_playlists WHERE id = $1 AND user_id = $2
`

type DeletePlaylistParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, deletePlaylist, arg.ID, arg.UserID)
	return err
}

const getMaxSongPosition = `-- name: GetMaxSongPosition :one
SELECT COALESCE(MAX(position), 0)::INT AS last_position FROM local_playlist_tracks WHERE playlist_id = $1
`

func (q *Queries) GetMaxSongPosition(ctx context.Context, playlistID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaxSongPosition, playlistID)
	var last_position int32
	err := row.Scan(&last_position)
	return last_position, err
}

const getPlaylistByID = `-- name: GetPlaylistByID :one
SELECT id, user_id, name, description, image_url, spotify_playlist_id, snapshot_id, is_public, last_synced_at, created_at, updated_at FROM local_playlists WHERE id = $1
`

func (q *Queries) GetPlaylistByID(ctx context.Context, id uuid.UUID) (LocalPlaylist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistByID, id)
	var i LocalPlaylist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.SpotifyPlaylistID,
		&i.SnapshotID,
		&i.IsPublic,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylistByIDWithTracks = `-- name: GetPlaylistByIDWithTracks :many
SELECT
    lp.id as playlist_id,
    lp.user_id,
    lp.name as playlist_name,
    lp.description,
    lp.image_url,
    lp.spotify_playlist_id,
    lp.snapshot_id,
    lp.is_public,
    lp.last_synced_at,
    lp.created_at,
    lp.updated_at,
    -- Track data (nullable for playlists with no tracks)
    lpt.spotify_track_id,
    lpt.position,
    lpt.updated_at as track_updated_at,
    st.name as track_name,
    st.duration_ms,
    st.disc_number,
    st.track_number,
    st.popularity,
    st.explicit,
    st.is_local,
    st.album_id,
    st.artist_ids,
    st.cached_at
FROM local_playlists lp
LEFT JOIN local_playlist_tracks lpt ON lp.id = lpt.playlist_id
LEFT JOIN spotify_tracks st ON lpt.spotify_track_id = st.id
WHERE lp.id = $1 AND lp.user_id = $2
ORDER BY lpt.position ASC
`

type GetPlaylistByIDWithTracksParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetPlaylistByIDWithTracksRow struct {
	PlaylistID        uuid.UUID
	UserID            uuid.UUID
	PlaylistName      string
	Description       sql.NullString
	ImageUrl          sql.NullString
	SpotifyPlaylistID sql.NullString
	SnapshotID        sql.NullString
	IsPublic          bool
	LastSyncedAt      sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
	SpotifyTrackID    sql.NullString
	Position          sql.NullInt32
	TrackUpdatedAt    sql.NullTime
	TrackName         sql.NullString
	DurationMs        sql.NullInt32
	DiscNumber        sql.NullInt32
	TrackNumber       sql.NullInt32
	Popularity        sql.NullInt32
	Explicit          sql.NullBool
	IsLocal           sql.NullBool
	AlbumID           sql.NullString
	ArtistIds         []string
	CachedAt          sql.NullTime
}

func (q *Queries) GetPlaylistByIDWithTracks(ctx context.Context, arg GetPlaylistByIDWithTracksParams) ([]GetPlaylistByIDWithTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistByIDWithTracks, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlaylistByIDWithTracksRow
	for rows.Next() {
		var i GetPlaylistByIDWithTracksRow
		if err := rows.Scan(
			&i.PlaylistID,
			&i.UserID,
			&i.PlaylistName,
			&i.Description,
			&i.ImageUrl,
			&i.SpotifyPlaylistID,
			&i.SnapshotID,
			&i.IsPublic,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SpotifyTrackID,
			&i.Position,
			&i.TrackUpdatedAt,
			&i.TrackName,
			&i.DurationMs,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.Popularity,
			&i.Explicit,
			&i.IsLocal,
			&i.AlbumID,
			pq.Array(&i.ArtistIds),
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistBySpotifyIDAndUserID = `-- name: GetPlaylistBySpotifyIDAndUserID :one
SELECT id, user_id, name, description, image_url, spotify_playlist_id, snapshot_id, is_public, last_synced_at, created_at, updated_at FROM local_playlists WHERE spotify_playlist_id = $1 AND user_id = $2 ORDER BY name DESC
`

type GetPlaylistBySpotifyIDAndUserIDParams struct {
	SpotifyPlaylistID sql.NullString
	UserID            uuid.UUID
}

func (q *Queries) GetPlaylistBySpotifyIDAndUserID(ctx context.Context, arg GetPlaylistBySpotifyIDAndUserIDParams) (LocalPlaylist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistBySpotifyIDAndUserID, arg.SpotifyPlaylistID, arg.UserID)
	var i LocalPlaylist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.SpotifyPlaylistID,
		&i.SnapshotID,
		&i.IsPublic,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylistByUserIDAndID = `-- name: GetPlaylistByUserIDAndID :one
SELECT id, user_id, name, description, image_url, spotify_playlist_id, snapshot_id, is_public, last_synced_at, created_at, updated_at FROM local_playlists WHERE id = $1 AND user_id = $2
`

type GetPlaylistByUserIDAndIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetPlaylistByUserIDAndID(ctx context.Context, arg GetPlaylistByUserIDAndIDParams) (LocalPlaylist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistByUserIDAndID, arg.ID, arg.UserID)
	var i LocalPlaylist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.SpotifyPlaylistID,
		&i.SnapshotID,
		&i.IsPublic,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylistSongByID = `-- name: GetPlaylistSongByID :one
SELECT playlist_id, spotify_track_id, position, updated_at FROM local_playlist_tracks WHERE playlist_id = $1 AND spotify_track_id = $2
`

type GetPlaylistSongByIDParams struct {
	PlaylistID     uuid.UUID
	SpotifyTrackID string
}

func (q *Queries) GetPlaylistSongByID(ctx context.Context, arg GetPlaylistSongByIDParams) (LocalPlaylistTrack, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistSongByID, arg.PlaylistID, arg.SpotifyTrackID)
	var i LocalPlaylistTrack
	err := row.Scan(
		&i.PlaylistID,
		&i.SpotifyTrackID,
		&i.Position,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylistSongs = `-- name: GetPlaylistSongs :many
SELECT playlist_id, spotify_track_id, position, updated_at FROM local_playlist_tracks WHERE playlist_id = $1 ORDER BY position
`

func (q *Queries) GetPlaylistSongs(ctx context.Context, playlistID uuid.UUID) ([]LocalPlaylistTrack, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistSongs, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalPlaylistTrack
	for rows.Next() {
		var i LocalPlaylistTrack
		if err := rows.Scan(
			&i.PlaylistID,
			&i.SpotifyTrackID,
			&i.Position,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistSongsWithTrackData = `-- name: GetPlaylistSongsWithTrackData :many
SELECT 
    lpt.spotify_track_id,
    lpt.position,
    lpt.updated_at,
    st.name AS track_name,
    st.duration_ms AS track_duration_ms,
    st.album_id AS track_album_id,
    st.artist_ids AS track_artist_ids
FROM local_playlist_tracks lpt
JOIN spotify_tracks st ON lpt.spotify_track_id = st.id
WHERE lpt.playlist_id = $1 
ORDER BY lpt.position
`

type GetPlaylistSongsWithTrackDataRow struct {
	SpotifyTrackID  string
	Position        int32
	UpdatedAt       time.Time
	TrackName       string
	TrackDurationMs int32
	TrackAlbumID    string
	TrackArtistIds  []string
}

func (q *Queries) GetPlaylistSongsWithTrackData(ctx context.Context, playlistID uuid.UUID) ([]GetPlaylistSongsWithTrackDataRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistSongsWithTrackData, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlaylistSongsWithTrackDataRow
	for rows.Next() {
		var i GetPlaylistSongsWithTrackDataRow
		if err := rows.Scan(
			&i.SpotifyTrackID,
			&i.Position,
			&i.UpdatedAt,
			&i.TrackName,
			&i.TrackDurationMs,
			&i.TrackAlbumID,
			pq.Array(&i.TrackArtistIds),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistsByUserID = `-- name: GetPlaylistsByUserID :many
SELECT id, user_id, name, description, image_url, spotify_playlist_id, snapshot_id, is_public, last_synced_at, created_at, updated_at FROM local_playlists WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetPlaylistsByUserID(ctx context.Context, userID uuid.UUID) ([]LocalPlaylist, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalPlaylist
	for rows.Next() {
		var i LocalPlaylist
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.SpotifyPlaylistID,
			&i.SnapshotID,
			&i.IsPublic,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistsByUserIDWithTracks = `-- name: GetPlaylistsByUserIDWithTracks :many
SELECT 
    lp.id as playlist_id,
    lp.user_id,
    lp.name as playlist_name,
    lp.description,
    lp.image_url,
    lp.spotify_playlist_id,
    lp.snapshot_id,
    lp.is_public,
    lp.last_synced_at,
    lp.created_at,
    lp.updated_at,
    -- Track data (nullable for playlists with no tracks)
    lpt.spotify_track_id,
    lpt.position,
    lpt.updated_at as track_updated_at,
    st.name as track_name,
    st.duration_ms,
    st.disc_number,
    st.track_number,
    st.popularity,
    st.explicit,
    st.is_local,
    st.album_id,
    st.artist_ids,
    st.cached_at
FROM local_playlists lp
LEFT JOIN local_playlist_tracks lpt ON lp.id = lpt.playlist_id
LEFT JOIN spotify_tracks st ON lpt.spotify_track_id = st.id
WHERE lp.user_id = $1
ORDER BY lp.created_at DESC, lpt.position ASC
`

type GetPlaylistsByUserIDWithTracksRow struct {
	PlaylistID        uuid.UUID
	UserID            uuid.UUID
	PlaylistName      string
	Description       sql.NullString
	ImageUrl          sql.NullString
	SpotifyPlaylistID sql.NullString
	SnapshotID        sql.NullString
	IsPublic          bool
	LastSyncedAt      sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
	SpotifyTrackID    sql.NullString
	Position          sql.NullInt32
	TrackUpdatedAt    sql.NullTime
	TrackName         sql.NullString
	DurationMs        sql.NullInt32
	DiscNumber        sql.NullInt32
	TrackNumber       sql.NullInt32
	Popularity        sql.NullInt32
	Explicit          sql.NullBool
	IsLocal           sql.NullBool
	AlbumID           sql.NullString
	ArtistIds         []string
	CachedAt          sql.NullTime
}

func (q *Queries) GetPlaylistsByUserIDWithTracks(ctx context.Context, userID uuid.UUID) ([]GetPlaylistsByUserIDWithTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistsByUserIDWithTracks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlaylistsByUserIDWithTracksRow
	for rows.Next() {
		var i GetPlaylistsByUserIDWithTracksRow
		if err := rows.Scan(
			&i.PlaylistID,
			&i.UserID,
			&i.PlaylistName,
			&i.Description,
			&i.ImageUrl,
			&i.SpotifyPlaylistID,
			&i.SnapshotID,
			&i.IsPublic,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SpotifyTrackID,
			&i.Position,
			&i.TrackUpdatedAt,
			&i.TrackName,
			&i.DurationMs,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.Popularity,
			&i.Explicit,
			&i.IsLocal,
			&i.AlbumID,
			pq.Array(&i.ArtistIds),
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSongFromPlaylist = `-- name: RemoveSongFromPlaylist :exec
DELETE FROM local_playlist_tracks WHERE playlist_id = $1 AND spotify_track_id = $2
`

type RemoveSongFromPlaylistParams struct {
	PlaylistID     uuid.UUID
	SpotifyTrackID string
}

func (q *Queries) RemoveSongFromPlaylist(ctx context.Context, arg RemoveSongFromPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, removeSongFromPlaylist, arg.PlaylistID, arg.SpotifyTrackID)
	return err
}

const updateSongPosition = `-- name: UpdateSongPosition :exec
UPDATE local_playlist_tracks SET position = $3 WHERE spotify_track_id = $2 AND playlist_id = $1
`

type UpdateSongPositionParams struct {
	PlaylistID     uuid.UUID
	SpotifyTrackID string
	Position       int32
}

func (q *Queries) UpdateSongPosition(ctx context.Context, arg UpdateSongPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateSongPosition, arg.PlaylistID, arg.SpotifyTrackID, arg.Position)
	return err
}

const upsertPlaylist = `-- name: UpsertPlaylist :one
INSERT INTO local_playlists (
    id, user_id, name, description, image_url,
    spotify_playlist_id, snapshot_id, is_public,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
ON CONFLICT (id)
DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    spotify_playlist_id = EXCLUDED.spotify_playlist_id,
    snapshot_id = EXCLUDED.snapshot_id,
    is_public = EXCLUDED.is_public,
    updated_at = NOW()
RETURNING id, user_id, name, description, image_url, spotify_playlist_id, snapshot_id, is_public, last_synced_at, created_at, updated_at
`

type UpsertPlaylistParams struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Name              string
	Description       sql.NullString
	ImageUrl          sql.NullString
	SpotifyPlaylistID sql.NullString
	SnapshotID        sql.NullString
	IsPublic          bool
}

// Playlist operations
func (q *Queries) UpsertPlaylist(ctx context.Context, arg UpsertPlaylistParams) (LocalPlaylist, error) {
	row := q.db.QueryRowContext(ctx, upsertPlaylist,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.SpotifyPlaylistID,
		arg.SnapshotID,
		arg.IsPublic,
	)
	var i LocalPlaylist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.SpotifyPlaylistID,
		&i.SnapshotID,
		&i.IsPublic,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
