// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: playlists.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addSongToPlaylist = `-- name: AddSongToPlaylist :one
INSERT INTO playlist_songs (id, playlist_id, spotify_track_id, position, track_name, artist_name, album_name, duration_ms, added_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
RETURNING id, playlist_id, spotify_track_id, spotify_album_id, spotify_artist_id, track_name, album_name, artist_name, position, duration_ms, added_at, updated_at
`

type AddSongToPlaylistParams struct {
	ID             uuid.UUID
	PlaylistID     uuid.UUID
	SpotifyTrackID string
	Position       int32
	TrackName      string
	ArtistName     string
	AlbumName      string
	DurationMs     int32
}

// Playlist songs operations
func (q *Queries) AddSongToPlaylist(ctx context.Context, arg AddSongToPlaylistParams) (PlaylistSong, error) {
	row := q.db.QueryRowContext(ctx, addSongToPlaylist,
		arg.ID,
		arg.PlaylistID,
		arg.SpotifyTrackID,
		arg.Position,
		arg.TrackName,
		arg.ArtistName,
		arg.AlbumName,
		arg.DurationMs,
	)
	var i PlaylistSong
	err := row.Scan(
		&i.ID,
		&i.PlaylistID,
		&i.SpotifyTrackID,
		&i.SpotifyAlbumID,
		&i.SpotifyArtistID,
		&i.TrackName,
		&i.AlbumName,
		&i.ArtistName,
		&i.Position,
		&i.DurationMs,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearPlaylistSongs = `-- name: ClearPlaylistSongs :exec
DELETE FROM playlist_songs WHERE playlist_id = $1
`

func (q *Queries) ClearPlaylistSongs(ctx context.Context, playlistID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearPlaylistSongs, playlistID)
	return err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO local_playlists (id, user_id, name, description, spotify_playlist_id, is_public, sync_with_spotify, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, user_id, name, description, spotify_playlist_id, is_public, sync_with_spotify, last_synced_at, created_at, updated_at
`

type CreatePlaylistParams struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Name              string
	Description       sql.NullString
	SpotifyPlaylistID sql.NullString
	IsPublic          bool
	SyncWithSpotify   bool
}

// Playlist operations
func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (LocalPlaylist, error) {
	row := q.db.QueryRowContext(ctx, createPlaylist,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.SpotifyPlaylistID,
		arg.IsPublic,
		arg.SyncWithSpotify,
	)
	var i LocalPlaylist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.SpotifyPlaylistID,
		&i.IsPublic,
		&i.SyncWithSpotify,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM local_playlists WHERE id = $1 AND user_id = $2
`

type DeletePlaylistParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, deletePlaylist, arg.ID, arg.UserID)
	return err
}

const getMaxSongPosition = `-- name: GetMaxSongPosition :one
SELECT COALESCE(MAX(position), 0)::INT AS last_position FROM playlist_songs WHERE playlist_id = $1
`

func (q *Queries) GetMaxSongPosition(ctx context.Context, playlistID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaxSongPosition, playlistID)
	var last_position int32
	err := row.Scan(&last_position)
	return last_position, err
}

const getPlaylistByID = `-- name: GetPlaylistByID :one
SELECT id, user_id, name, description, spotify_playlist_id, is_public, sync_with_spotify, last_synced_at, created_at, updated_at FROM local_playlists WHERE id = $1
`

func (q *Queries) GetPlaylistByID(ctx context.Context, id uuid.UUID) (LocalPlaylist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistByID, id)
	var i LocalPlaylist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.SpotifyPlaylistID,
		&i.IsPublic,
		&i.SyncWithSpotify,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylistByUserIDAndID = `-- name: GetPlaylistByUserIDAndID :one
SELECT id, user_id, name, description, spotify_playlist_id, is_public, sync_with_spotify, last_synced_at, created_at, updated_at FROM local_playlists WHERE id = $1 AND user_id = $2
`

type GetPlaylistByUserIDAndIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetPlaylistByUserIDAndID(ctx context.Context, arg GetPlaylistByUserIDAndIDParams) (LocalPlaylist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistByUserIDAndID, arg.ID, arg.UserID)
	var i LocalPlaylist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.SpotifyPlaylistID,
		&i.IsPublic,
		&i.SyncWithSpotify,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylistSongByID = `-- name: GetPlaylistSongByID :one
SELECT id, playlist_id, spotify_track_id, spotify_album_id, spotify_artist_id, track_name, album_name, artist_name, position, duration_ms, added_at, updated_at FROM playlist_songs WHERE id = $1 AND playlist_id = $2
`

type GetPlaylistSongByIDParams struct {
	ID         uuid.UUID
	PlaylistID uuid.UUID
}

func (q *Queries) GetPlaylistSongByID(ctx context.Context, arg GetPlaylistSongByIDParams) (PlaylistSong, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistSongByID, arg.ID, arg.PlaylistID)
	var i PlaylistSong
	err := row.Scan(
		&i.ID,
		&i.PlaylistID,
		&i.SpotifyTrackID,
		&i.SpotifyAlbumID,
		&i.SpotifyArtistID,
		&i.TrackName,
		&i.AlbumName,
		&i.ArtistName,
		&i.Position,
		&i.DurationMs,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylistSongs = `-- name: GetPlaylistSongs :many
SELECT id, playlist_id, spotify_track_id, spotify_album_id, spotify_artist_id, track_name, album_name, artist_name, position, duration_ms, added_at, updated_at FROM playlist_songs WHERE playlist_id = $1 ORDER BY position
`

func (q *Queries) GetPlaylistSongs(ctx context.Context, playlistID uuid.UUID) ([]PlaylistSong, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistSongs, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaylistSong
	for rows.Next() {
		var i PlaylistSong
		if err := rows.Scan(
			&i.ID,
			&i.PlaylistID,
			&i.SpotifyTrackID,
			&i.SpotifyAlbumID,
			&i.SpotifyArtistID,
			&i.TrackName,
			&i.AlbumName,
			&i.ArtistName,
			&i.Position,
			&i.DurationMs,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistsByUserID = `-- name: GetPlaylistsByUserID :many
SELECT id, user_id, name, description, spotify_playlist_id, is_public, sync_with_spotify, last_synced_at, created_at, updated_at FROM local_playlists WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetPlaylistsByUserID(ctx context.Context, userID uuid.UUID) ([]LocalPlaylist, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalPlaylist
	for rows.Next() {
		var i LocalPlaylist
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.SpotifyPlaylistID,
			&i.IsPublic,
			&i.SyncWithSpotify,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSongFromPlaylist = `-- name: RemoveSongFromPlaylist :exec
DELETE FROM playlist_songs WHERE id = $1 AND playlist_id = $2
`

type RemoveSongFromPlaylistParams struct {
	ID         uuid.UUID
	PlaylistID uuid.UUID
}

func (q *Queries) RemoveSongFromPlaylist(ctx context.Context, arg RemoveSongFromPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, removeSongFromPlaylist, arg.ID, arg.PlaylistID)
	return err
}

const updatePlaylist = `-- name: UpdatePlaylist :exec
UPDATE local_playlists 
SET name = $2, description = $3, is_public = $4, sync_with_spotify = $5, updated_at = NOW()
WHERE id = $1 AND user_id = $6
`

type UpdatePlaylistParams struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	IsPublic        bool
	SyncWithSpotify bool
	UserID          uuid.UUID
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaylist,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
		arg.SyncWithSpotify,
		arg.UserID,
	)
	return err
}

const updatePlaylistSyncTime = `-- name: UpdatePlaylistSyncTime :exec
UPDATE local_playlists 
SET last_synced_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type UpdatePlaylistSyncTimeParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UpdatePlaylistSyncTime(ctx context.Context, arg UpdatePlaylistSyncTimeParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaylistSyncTime, arg.ID, arg.UserID)
	return err
}

const updateSongPosition = `-- name: UpdateSongPosition :exec
UPDATE playlist_songs SET position = $2 WHERE id = $1
`

type UpdateSongPositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) UpdateSongPosition(ctx context.Context, arg UpdateSongPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateSongPosition, arg.ID, arg.Position)
	return err
}
