// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: songs.sql

package database

import (
	"context"
)

const getSongBySpotifyID = `-- name: GetSongBySpotifyID :one
SELECT spotify_track_id, spotify_album_id, spotify_artist_id, track_name, album_name, artist_name, artist_image_url, album_image_url, duration_ms, created_at, updated_at FROM songs WHERE spotify_track_id = $1
`

func (q *Queries) GetSongBySpotifyID(ctx context.Context, spotifyTrackID string) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSongBySpotifyID, spotifyTrackID)
	var i Song
	err := row.Scan(
		&i.SpotifyTrackID,
		&i.SpotifyAlbumID,
		&i.SpotifyArtistID,
		&i.TrackName,
		&i.AlbumName,
		&i.ArtistName,
		&i.ArtistImageUrl,
		&i.AlbumImageUrl,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSong = `-- name: UpsertSong :one
INSERT INTO songs (spotify_track_id,
    spotify_album_id,
    spotify_artist_id,
    track_name,
    album_name,
    artist_name,
    album_image_url,
    artist_image_url,
    duration_ms,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
ON CONFLICT (spotify_track_id) DO UPDATE SET
    spotify_album_id = EXCLUDED.spotify_album_id,
    spotify_artist_id = EXCLUDED.spotify_artist_id,
    track_name = EXCLUDED.track_name,
    album_name = EXCLUDED.album_name,
    artist_name = EXCLUDED.artist_name,
    album_image_url = EXCLUDED.album_image_url,
    artist_image_url = EXCLUDED.artist_image_url,
    duration_ms = EXCLUDED.duration_ms,
    created_at = EXCLUDED.created_at,
    updated_at = NOW()
RETURNING spotify_track_id, spotify_album_id, spotify_artist_id, track_name, album_name, artist_name, artist_image_url, album_image_url, duration_ms, created_at, updated_at
`

type UpsertSongParams struct {
	SpotifyTrackID  string
	SpotifyAlbumID  string
	SpotifyArtistID string
	TrackName       string
	AlbumName       string
	ArtistName      string
	AlbumImageUrl   string
	ArtistImageUrl  string
	DurationMs      int32
}

func (q *Queries) UpsertSong(ctx context.Context, arg UpsertSongParams) (Song, error) {
	row := q.db.QueryRowContext(ctx, upsertSong,
		arg.SpotifyTrackID,
		arg.SpotifyAlbumID,
		arg.SpotifyArtistID,
		arg.TrackName,
		arg.AlbumName,
		arg.ArtistName,
		arg.AlbumImageUrl,
		arg.ArtistImageUrl,
		arg.DurationMs,
	)
	var i Song
	err := row.Scan(
		&i.SpotifyTrackID,
		&i.SpotifyAlbumID,
		&i.SpotifyArtistID,
		&i.TrackName,
		&i.AlbumName,
		&i.ArtistName,
		&i.ArtistImageUrl,
		&i.AlbumImageUrl,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
