// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: spotify_data.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const batchGetSpotifyArtists = `-- name: BatchGetSpotifyArtists :many
SELECT id, name, image_url, popularity, followers_total, genres, cached_at, updated_at FROM spotify_artists WHERE id = ANY($1::text[])
`

func (q *Queries) BatchGetSpotifyArtists(ctx context.Context, dollar_1 []string) ([]SpotifyArtist, error) {
	rows, err := q.db.QueryContext(ctx, batchGetSpotifyArtists, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpotifyArtist
	for rows.Next() {
		var i SpotifyArtist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Popularity,
			&i.FollowersTotal,
			pq.Array(&i.Genres),
			&i.CachedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupOldSpotifyAlbums = `-- name: CleanupOldSpotifyAlbums :exec
DELETE FROM spotify_albums WHERE cached_at < $1
`

func (q *Queries) CleanupOldSpotifyAlbums(ctx context.Context, cachedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupOldSpotifyAlbums, cachedAt)
	return err
}

const cleanupOldSpotifyArtists = `-- name: CleanupOldSpotifyArtists :exec

DELETE FROM spotify_artists WHERE cached_at < $1
`

// =============================================================================
// CACHE MANAGEMENT OPERATIONS
// =============================================================================
func (q *Queries) CleanupOldSpotifyArtists(ctx context.Context, cachedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupOldSpotifyArtists, cachedAt)
	return err
}

const cleanupOldSpotifyPlaylistsCache = `-- name: CleanupOldSpotifyPlaylistsCache :exec
DELETE FROM spotify_playlists_cache WHERE cached_at < $1
`

func (q *Queries) CleanupOldSpotifyPlaylistsCache(ctx context.Context, cachedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupOldSpotifyPlaylistsCache, cachedAt)
	return err
}

const cleanupOldSpotifyTracks = `-- name: CleanupOldSpotifyTracks :exec
DELETE FROM spotify_tracks WHERE cached_at < $1
`

func (q *Queries) CleanupOldSpotifyTracks(ctx context.Context, cachedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupOldSpotifyTracks, cachedAt)
	return err
}

const clearAlbumArtists = `-- name: ClearAlbumArtists :exec
DELETE FROM spotify_album_artists WHERE album_id = $1
`

func (q *Queries) ClearAlbumArtists(ctx context.Context, albumID string) error {
	_, err := q.db.ExecContext(ctx, clearAlbumArtists, albumID)
	return err
}

const clearTrackArtists = `-- name: ClearTrackArtists :exec
DELETE FROM spotify_track_artists WHERE track_id = $1
`

func (q *Queries) ClearTrackArtists(ctx context.Context, trackID string) error {
	_, err := q.db.ExecContext(ctx, clearTrackArtists, trackID)
	return err
}

const getCacheStats = `-- name: GetCacheStats :one
SELECT 
    (SELECT COUNT(*) FROM spotify_artists) as artists_count,
    (SELECT COUNT(*) FROM spotify_albums) as albums_count,
    (SELECT COUNT(*) FROM spotify_tracks) as tracks_count,
    (SELECT COUNT(*) FROM spotify_playlists_cache) as playlists_count
`

type GetCacheStatsRow struct {
	ArtistsCount   int64
	AlbumsCount    int64
	TracksCount    int64
	PlaylistsCount int64
}

func (q *Queries) GetCacheStats(ctx context.Context) (GetCacheStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getCacheStats)
	var i GetCacheStatsRow
	err := row.Scan(
		&i.ArtistsCount,
		&i.AlbumsCount,
		&i.TracksCount,
		&i.PlaylistsCount,
	)
	return i, err
}

const getMultipleSpotifyTracksWithRelations = `-- name: GetMultipleSpotifyTracksWithRelations :many
SELECT 
    t.id, t.name, t.duration_ms, t.disc_number, t.track_number,
    t.popularity, t.explicit, t.preview_url, t.is_local, t.cached_at, t.updated_at,
    -- Album data
    a.id as album_id, a.name as album_name, a.album_type, a.release_date,
    a.image_url as album_image_url, a.label as album_label,
    -- Primary artist data (for efficient playlist display)
    ar.id as artist_id, ar.name as artist_name, ta.is_primary as artist_is_primary
FROM spotify_tracks t
LEFT JOIN spotify_albums a ON t.album_id = a.id
LEFT JOIN spotify_track_artists ta ON t.id = ta.track_id AND ta.is_primary = true
LEFT JOIN spotify_artists ar ON ta.artist_id = ar.id
WHERE t.id = ANY($1::text[])
ORDER BY t.id
`

type GetMultipleSpotifyTracksWithRelationsRow struct {
	ID              string
	Name            string
	DurationMs      int32
	DiscNumber      sql.NullInt32
	TrackNumber     sql.NullInt32
	Popularity      sql.NullInt32
	Explicit        sql.NullBool
	PreviewUrl      sql.NullString
	IsLocal         sql.NullBool
	CachedAt        time.Time
	UpdatedAt       time.Time
	AlbumID         sql.NullString
	AlbumName       sql.NullString
	AlbumType       sql.NullString
	ReleaseDate     sql.NullTime
	AlbumImageUrl   sql.NullString
	AlbumLabel      sql.NullString
	ArtistID        sql.NullString
	ArtistName      sql.NullString
	ArtistIsPrimary sql.NullBool
}

func (q *Queries) GetMultipleSpotifyTracksWithRelations(ctx context.Context, dollar_1 []string) ([]GetMultipleSpotifyTracksWithRelationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMultipleSpotifyTracksWithRelations, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMultipleSpotifyTracksWithRelationsRow
	for rows.Next() {
		var i GetMultipleSpotifyTracksWithRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationMs,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.Popularity,
			&i.Explicit,
			&i.PreviewUrl,
			&i.IsLocal,
			&i.CachedAt,
			&i.UpdatedAt,
			&i.AlbumID,
			&i.AlbumName,
			&i.AlbumType,
			&i.ReleaseDate,
			&i.AlbumImageUrl,
			&i.AlbumLabel,
			&i.ArtistID,
			&i.ArtistName,
			&i.ArtistIsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpotifyAlbum = `-- name: GetSpotifyAlbum :one

SELECT id, name, album_type, release_date, release_date_precision, total_tracks, image_url, label, popularity, cached_at, updated_at FROM spotify_albums WHERE id = $1
`

// =============================================================================
// ALBUM OPERATIONS
// =============================================================================
func (q *Queries) GetSpotifyAlbum(ctx context.Context, id string) (SpotifyAlbum, error) {
	row := q.db.QueryRowContext(ctx, getSpotifyAlbum, id)
	var i SpotifyAlbum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AlbumType,
		&i.ReleaseDate,
		&i.ReleaseDatePrecision,
		&i.TotalTracks,
		&i.ImageUrl,
		&i.Label,
		&i.Popularity,
		&i.CachedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpotifyAlbumWithArtists = `-- name: GetSpotifyAlbumWithArtists :many
SELECT 
    a.id, a.name, a.album_type, a.release_date, a.release_date_precision,
    a.total_tracks, a.image_url, a.label, a.popularity, a.cached_at, a.updated_at,
    ar.id as artist_id, ar.name as artist_name, ar.image_url as artist_image_url,
    ar.popularity as artist_popularity, ar.followers_total as artist_followers_total,
    ar.genres as artist_genres
FROM spotify_albums a
LEFT JOIN spotify_album_artists aa ON a.id = aa.album_id  
LEFT JOIN spotify_artists ar ON aa.artist_id = ar.id
WHERE a.id = $1
`

type GetSpotifyAlbumWithArtistsRow struct {
	ID                   string
	Name                 string
	AlbumType            string
	ReleaseDate          sql.NullTime
	ReleaseDatePrecision sql.NullString
	TotalTracks          sql.NullInt32
	ImageUrl             sql.NullString
	Label                sql.NullString
	Popularity           sql.NullInt32
	CachedAt             time.Time
	UpdatedAt            time.Time
	ArtistID             sql.NullString
	ArtistName           sql.NullString
	ArtistImageUrl       sql.NullString
	ArtistPopularity     sql.NullInt32
	ArtistFollowersTotal sql.NullInt32
	ArtistGenres         []string
}

func (q *Queries) GetSpotifyAlbumWithArtists(ctx context.Context, id string) ([]GetSpotifyAlbumWithArtistsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpotifyAlbumWithArtists, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpotifyAlbumWithArtistsRow
	for rows.Next() {
		var i GetSpotifyAlbumWithArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AlbumType,
			&i.ReleaseDate,
			&i.ReleaseDatePrecision,
			&i.TotalTracks,
			&i.ImageUrl,
			&i.Label,
			&i.Popularity,
			&i.CachedAt,
			&i.UpdatedAt,
			&i.ArtistID,
			&i.ArtistName,
			&i.ArtistImageUrl,
			&i.ArtistPopularity,
			&i.ArtistFollowersTotal,
			pq.Array(&i.ArtistGenres),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpotifyArtist = `-- name: GetSpotifyArtist :one

SELECT id, name, image_url, popularity, followers_total, genres, cached_at, updated_at FROM spotify_artists WHERE id = $1
`

// =============================================================================
// ARTIST OPERATIONS
// =============================================================================
func (q *Queries) GetSpotifyArtist(ctx context.Context, id string) (SpotifyArtist, error) {
	row := q.db.QueryRowContext(ctx, getSpotifyArtist, id)
	var i SpotifyArtist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Popularity,
		&i.FollowersTotal,
		pq.Array(&i.Genres),
		&i.CachedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpotifyPlaylistCache = `-- name: GetSpotifyPlaylistCache :one

SELECT id, name, description, owner_id, owner_display_name, public, collaborative, followers_total, total_tracks, image_url, cached_at, updated_at FROM spotify_playlists_cache WHERE id = $1
`

// =============================================================================
// PLAYLIST CACHE OPERATIONS
// =============================================================================
func (q *Queries) GetSpotifyPlaylistCache(ctx context.Context, id string) (SpotifyPlaylistsCache, error) {
	row := q.db.QueryRowContext(ctx, getSpotifyPlaylistCache, id)
	var i SpotifyPlaylistsCache
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerDisplayName,
		&i.Public,
		&i.Collaborative,
		&i.FollowersTotal,
		&i.TotalTracks,
		&i.ImageUrl,
		&i.CachedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpotifyTrack = `-- name: GetSpotifyTrack :one

SELECT id, name, album_id, duration_ms, disc_number, track_number, popularity, explicit, preview_url, is_local, cached_at, updated_at FROM spotify_tracks WHERE id = $1
`

// =============================================================================
// TRACK OPERATIONS
// =============================================================================
func (q *Queries) GetSpotifyTrack(ctx context.Context, id string) (SpotifyTrack, error) {
	row := q.db.QueryRowContext(ctx, getSpotifyTrack, id)
	var i SpotifyTrack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AlbumID,
		&i.DurationMs,
		&i.DiscNumber,
		&i.TrackNumber,
		&i.Popularity,
		&i.Explicit,
		&i.PreviewUrl,
		&i.IsLocal,
		&i.CachedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpotifyTrackWithRelations = `-- name: GetSpotifyTrackWithRelations :many
SELECT 
    t.id, t.name, t.duration_ms, t.disc_number, t.track_number, 
    t.popularity, t.explicit, t.preview_url, t.is_local, t.cached_at, t.updated_at,
    -- Album data
    a.id as album_id, a.name as album_name, a.album_type, a.release_date,
    a.release_date_precision, a.total_tracks, a.image_url as album_image_url,
    a.label as album_label, a.popularity as album_popularity,
    -- Track artist data (including primary flag)
    ar.id as artist_id, ar.name as artist_name, ar.image_url as artist_image_url,
    ar.popularity as artist_popularity, ar.followers_total as artist_followers_total,
    ar.genres as artist_genres, ta.is_primary as artist_is_primary
FROM spotify_tracks t
LEFT JOIN spotify_albums a ON t.album_id = a.id
LEFT JOIN spotify_track_artists ta ON t.id = ta.track_id
LEFT JOIN spotify_artists ar ON ta.artist_id = ar.id  
WHERE t.id = $1
ORDER BY ta.is_primary DESC, ar.name
`

type GetSpotifyTrackWithRelationsRow struct {
	ID                   string
	Name                 string
	DurationMs           int32
	DiscNumber           sql.NullInt32
	TrackNumber          sql.NullInt32
	Popularity           sql.NullInt32
	Explicit             sql.NullBool
	PreviewUrl           sql.NullString
	IsLocal              sql.NullBool
	CachedAt             time.Time
	UpdatedAt            time.Time
	AlbumID              sql.NullString
	AlbumName            sql.NullString
	AlbumType            sql.NullString
	ReleaseDate          sql.NullTime
	ReleaseDatePrecision sql.NullString
	TotalTracks          sql.NullInt32
	AlbumImageUrl        sql.NullString
	AlbumLabel           sql.NullString
	AlbumPopularity      sql.NullInt32
	ArtistID             sql.NullString
	ArtistName           sql.NullString
	ArtistImageUrl       sql.NullString
	ArtistPopularity     sql.NullInt32
	ArtistFollowersTotal sql.NullInt32
	ArtistGenres         []string
	ArtistIsPrimary      sql.NullBool
}

func (q *Queries) GetSpotifyTrackWithRelations(ctx context.Context, id string) ([]GetSpotifyTrackWithRelationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpotifyTrackWithRelations, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpotifyTrackWithRelationsRow
	for rows.Next() {
		var i GetSpotifyTrackWithRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationMs,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.Popularity,
			&i.Explicit,
			&i.PreviewUrl,
			&i.IsLocal,
			&i.CachedAt,
			&i.UpdatedAt,
			&i.AlbumID,
			&i.AlbumName,
			&i.AlbumType,
			&i.ReleaseDate,
			&i.ReleaseDatePrecision,
			&i.TotalTracks,
			&i.AlbumImageUrl,
			&i.AlbumLabel,
			&i.AlbumPopularity,
			&i.ArtistID,
			&i.ArtistName,
			&i.ArtistImageUrl,
			&i.ArtistPopularity,
			&i.ArtistFollowersTotal,
			pq.Array(&i.ArtistGenres),
			&i.ArtistIsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSpotifyAlbumsByName = `-- name: SearchSpotifyAlbumsByName :many
SELECT a.id, a.name, a.album_type, a.release_date, a.total_tracks, a.image_url,
       string_agg(ar.name, ', ') as artist_names
FROM spotify_albums a
LEFT JOIN spotify_album_artists aa ON a.id = aa.album_id
LEFT JOIN spotify_artists ar ON aa.artist_id = ar.id
WHERE a.name ILIKE '%' || $1 || '%'
GROUP BY a.id, a.name, a.album_type, a.release_date, a.total_tracks, a.image_url
ORDER BY a.popularity DESC, a.name
LIMIT $2
`

type SearchSpotifyAlbumsByNameParams struct {
	Column1 sql.NullString
	Limit   int32
}

type SearchSpotifyAlbumsByNameRow struct {
	ID          string
	Name        string
	AlbumType   string
	ReleaseDate sql.NullTime
	TotalTracks sql.NullInt32
	ImageUrl    sql.NullString
	ArtistNames []byte
}

func (q *Queries) SearchSpotifyAlbumsByName(ctx context.Context, arg SearchSpotifyAlbumsByNameParams) ([]SearchSpotifyAlbumsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSpotifyAlbumsByName, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSpotifyAlbumsByNameRow
	for rows.Next() {
		var i SearchSpotifyAlbumsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AlbumType,
			&i.ReleaseDate,
			&i.TotalTracks,
			&i.ImageUrl,
			&i.ArtistNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSpotifyArtistsByName = `-- name: SearchSpotifyArtistsByName :many

SELECT id, name, image_url, popularity, followers_total, genres
FROM spotify_artists 
WHERE name ILIKE '%' || $1 || '%'
ORDER BY popularity DESC, name
LIMIT $2
`

type SearchSpotifyArtistsByNameParams struct {
	Column1 sql.NullString
	Limit   int32
}

type SearchSpotifyArtistsByNameRow struct {
	ID             string
	Name           string
	ImageUrl       sql.NullString
	Popularity     sql.NullInt32
	FollowersTotal sql.NullInt32
	Genres         []string
}

// =============================================================================
// EFFICIENT SEARCH OPERATIONS
// =============================================================================
func (q *Queries) SearchSpotifyArtistsByName(ctx context.Context, arg SearchSpotifyArtistsByNameParams) ([]SearchSpotifyArtistsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSpotifyArtistsByName, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSpotifyArtistsByNameRow
	for rows.Next() {
		var i SearchSpotifyArtistsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Popularity,
			&i.FollowersTotal,
			pq.Array(&i.Genres),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSpotifyTracksByName = `-- name: SearchSpotifyTracksByName :many
SELECT t.id, t.name, t.duration_ms, t.popularity, t.explicit,
       a.name as album_name, a.image_url as album_image_url,
       string_agg(ar.name, ', ') as artist_names
FROM spotify_tracks t
LEFT JOIN spotify_albums a ON t.album_id = a.id
LEFT JOIN spotify_track_artists ta ON t.id = ta.track_id
LEFT JOIN spotify_artists ar ON ta.artist_id = ar.id
WHERE t.name ILIKE '%' || $1 || '%'
GROUP BY t.id, t.name, t.duration_ms, t.popularity, t.explicit, a.name, a.image_url
ORDER BY t.popularity DESC, t.name
LIMIT $2
`

type SearchSpotifyTracksByNameParams struct {
	Column1 sql.NullString
	Limit   int32
}

type SearchSpotifyTracksByNameRow struct {
	ID            string
	Name          string
	DurationMs    int32
	Popularity    sql.NullInt32
	Explicit      sql.NullBool
	AlbumName     sql.NullString
	AlbumImageUrl sql.NullString
	ArtistNames   []byte
}

func (q *Queries) SearchSpotifyTracksByName(ctx context.Context, arg SearchSpotifyTracksByNameParams) ([]SearchSpotifyTracksByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSpotifyTracksByName, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSpotifyTracksByNameRow
	for rows.Next() {
		var i SearchSpotifyTracksByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationMs,
			&i.Popularity,
			&i.Explicit,
			&i.AlbumName,
			&i.AlbumImageUrl,
			&i.ArtistNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAlbumArtist = `-- name: UpsertAlbumArtist :exec

INSERT INTO spotify_album_artists (album_id, artist_id)
VALUES ($1, $2)
ON CONFLICT (album_id, artist_id) DO NOTHING
`

type UpsertAlbumArtistParams struct {
	AlbumID  string
	ArtistID string
}

// =============================================================================
// RELATIONSHIP OPERATIONS
// =============================================================================
func (q *Queries) UpsertAlbumArtist(ctx context.Context, arg UpsertAlbumArtistParams) error {
	_, err := q.db.ExecContext(ctx, upsertAlbumArtist, arg.AlbumID, arg.ArtistID)
	return err
}

const upsertSpotifyAlbum = `-- name: UpsertSpotifyAlbum :one
INSERT INTO spotify_albums (id, name, album_type, release_date, release_date_precision, total_tracks, image_url, label, popularity, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    album_type = EXCLUDED.album_type,
    release_date = EXCLUDED.release_date,
    release_date_precision = EXCLUDED.release_date_precision,
    total_tracks = EXCLUDED.total_tracks,
    image_url = EXCLUDED.image_url,
    label = EXCLUDED.label,
    popularity = EXCLUDED.popularity,
    updated_at = EXCLUDED.updated_at
RETURNING id, name, album_type, release_date, release_date_precision, total_tracks, image_url, label, popularity, cached_at, updated_at
`

type UpsertSpotifyAlbumParams struct {
	ID                   string
	Name                 string
	AlbumType            string
	ReleaseDate          sql.NullTime
	ReleaseDatePrecision sql.NullString
	TotalTracks          sql.NullInt32
	ImageUrl             sql.NullString
	Label                sql.NullString
	Popularity           sql.NullInt32
}

func (q *Queries) UpsertSpotifyAlbum(ctx context.Context, arg UpsertSpotifyAlbumParams) (SpotifyAlbum, error) {
	row := q.db.QueryRowContext(ctx, upsertSpotifyAlbum,
		arg.ID,
		arg.Name,
		arg.AlbumType,
		arg.ReleaseDate,
		arg.ReleaseDatePrecision,
		arg.TotalTracks,
		arg.ImageUrl,
		arg.Label,
		arg.Popularity,
	)
	var i SpotifyAlbum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AlbumType,
		&i.ReleaseDate,
		&i.ReleaseDatePrecision,
		&i.TotalTracks,
		&i.ImageUrl,
		&i.Label,
		&i.Popularity,
		&i.CachedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSpotifyArtist = `-- name: UpsertSpotifyArtist :one
INSERT INTO spotify_artists (id, name, image_url, popularity, followers_total, genres, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    image_url = EXCLUDED.image_url,
    popularity = EXCLUDED.popularity,
    followers_total = EXCLUDED.followers_total,
    genres = EXCLUDED.genres,
    updated_at = EXCLUDED.updated_at
RETURNING id, name, image_url, popularity, followers_total, genres, cached_at, updated_at
`

type UpsertSpotifyArtistParams struct {
	ID             string
	Name           string
	ImageUrl       sql.NullString
	Popularity     sql.NullInt32
	FollowersTotal sql.NullInt32
	Genres         []string
}

func (q *Queries) UpsertSpotifyArtist(ctx context.Context, arg UpsertSpotifyArtistParams) (SpotifyArtist, error) {
	row := q.db.QueryRowContext(ctx, upsertSpotifyArtist,
		arg.ID,
		arg.Name,
		arg.ImageUrl,
		arg.Popularity,
		arg.FollowersTotal,
		pq.Array(arg.Genres),
	)
	var i SpotifyArtist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Popularity,
		&i.FollowersTotal,
		pq.Array(&i.Genres),
		&i.CachedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSpotifyPlaylistCache = `-- name: UpsertSpotifyPlaylistCache :one
INSERT INTO spotify_playlists_cache (id, name, description, owner_id, owner_display_name, public, collaborative, followers_total, total_tracks, image_url, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    owner_id = EXCLUDED.owner_id,
    owner_display_name = EXCLUDED.owner_display_name,
    public = EXCLUDED.public,
    collaborative = EXCLUDED.collaborative,
    followers_total = EXCLUDED.followers_total,
    total_tracks = EXCLUDED.total_tracks,
    image_url = EXCLUDED.image_url,
    updated_at = EXCLUDED.updated_at
RETURNING id, name, description, owner_id, owner_display_name, public, collaborative, followers_total, total_tracks, image_url, cached_at, updated_at
`

type UpsertSpotifyPlaylistCacheParams struct {
	ID               string
	Name             string
	Description      sql.NullString
	OwnerID          string
	OwnerDisplayName sql.NullString
	Public           sql.NullBool
	Collaborative    sql.NullBool
	FollowersTotal   sql.NullInt32
	TotalTracks      sql.NullInt32
	ImageUrl         sql.NullString
}

func (q *Queries) UpsertSpotifyPlaylistCache(ctx context.Context, arg UpsertSpotifyPlaylistCacheParams) (SpotifyPlaylistsCache, error) {
	row := q.db.QueryRowContext(ctx, upsertSpotifyPlaylistCache,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.OwnerDisplayName,
		arg.Public,
		arg.Collaborative,
		arg.FollowersTotal,
		arg.TotalTracks,
		arg.ImageUrl,
	)
	var i SpotifyPlaylistsCache
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerDisplayName,
		&i.Public,
		&i.Collaborative,
		&i.FollowersTotal,
		&i.TotalTracks,
		&i.ImageUrl,
		&i.CachedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSpotifyTrack = `-- name: UpsertSpotifyTrack :one
INSERT INTO spotify_tracks (id, name, album_id, duration_ms, disc_number, track_number, popularity, explicit, preview_url, is_local, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    album_id = EXCLUDED.album_id,
    duration_ms = EXCLUDED.duration_ms,
    disc_number = EXCLUDED.disc_number,
    track_number = EXCLUDED.track_number,
    popularity = EXCLUDED.popularity,
    explicit = EXCLUDED.explicit,
    preview_url = EXCLUDED.preview_url,
    is_local = EXCLUDED.is_local,
    updated_at = EXCLUDED.updated_at
RETURNING id, name, album_id, duration_ms, disc_number, track_number, popularity, explicit, preview_url, is_local, cached_at, updated_at
`

type UpsertSpotifyTrackParams struct {
	ID          string
	Name        string
	AlbumID     sql.NullString
	DurationMs  int32
	DiscNumber  sql.NullInt32
	TrackNumber sql.NullInt32
	Popularity  sql.NullInt32
	Explicit    sql.NullBool
	PreviewUrl  sql.NullString
	IsLocal     sql.NullBool
}

func (q *Queries) UpsertSpotifyTrack(ctx context.Context, arg UpsertSpotifyTrackParams) (SpotifyTrack, error) {
	row := q.db.QueryRowContext(ctx, upsertSpotifyTrack,
		arg.ID,
		arg.Name,
		arg.AlbumID,
		arg.DurationMs,
		arg.DiscNumber,
		arg.TrackNumber,
		arg.Popularity,
		arg.Explicit,
		arg.PreviewUrl,
		arg.IsLocal,
	)
	var i SpotifyTrack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AlbumID,
		&i.DurationMs,
		&i.DiscNumber,
		&i.TrackNumber,
		&i.Popularity,
		&i.Explicit,
		&i.PreviewUrl,
		&i.IsLocal,
		&i.CachedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTrackArtist = `-- name: UpsertTrackArtist :exec
INSERT INTO spotify_track_artists (track_id, artist_id, is_primary)
VALUES ($1, $2, $3)
ON CONFLICT (track_id, artist_id) DO UPDATE SET
    is_primary = EXCLUDED.is_primary
`

type UpsertTrackArtistParams struct {
	TrackID   string
	ArtistID  string
	IsPrimary sql.NullBool
}

func (q *Queries) UpsertTrackArtist(ctx context.Context, arg UpsertTrackArtistParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackArtist, arg.TrackID, arg.ArtistID, arg.IsPrimary)
	return err
}
