// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: spotify_data.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const cleanupOldSpotifyAlbums = `-- name: CleanupOldSpotifyAlbums :exec
DELETE FROM spotify_albums WHERE cached_at < $1
`

func (q *Queries) CleanupOldSpotifyAlbums(ctx context.Context, cachedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupOldSpotifyAlbums, cachedAt)
	return err
}

const cleanupOldSpotifyArtists = `-- name: CleanupOldSpotifyArtists :exec

DELETE FROM spotify_artists WHERE cached_at < $1
`

// =============================================================================
// CACHE MANAGEMENT OPERATIONS
// =============================================================================
func (q *Queries) CleanupOldSpotifyArtists(ctx context.Context, cachedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupOldSpotifyArtists, cachedAt)
	return err
}

const cleanupOldSpotifyPlaylists = `-- name: CleanupOldSpotifyPlaylists :exec
DELETE FROM spotify_playlists WHERE cached_at < $1
`

func (q *Queries) CleanupOldSpotifyPlaylists(ctx context.Context, cachedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupOldSpotifyPlaylists, cachedAt)
	return err
}

const cleanupOldSpotifyTracks = `-- name: CleanupOldSpotifyTracks :exec
DELETE FROM spotify_tracks WHERE cached_at < $1
`

func (q *Queries) CleanupOldSpotifyTracks(ctx context.Context, cachedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupOldSpotifyTracks, cachedAt)
	return err
}

const getCacheStats = `-- name: GetCacheStats :one
SELECT 
    (SELECT COUNT(*) FROM spotify_artists) as artists_count,
    (SELECT COUNT(*) FROM spotify_albums) as albums_count,
    (SELECT COUNT(*) FROM spotify_tracks) as tracks_count,
    (SELECT COUNT(*) FROM spotify_playlists) as playlists_count
`

type GetCacheStatsRow struct {
	ArtistsCount   int64
	AlbumsCount    int64
	TracksCount    int64
	PlaylistsCount int64
}

func (q *Queries) GetCacheStats(ctx context.Context) (GetCacheStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getCacheStats)
	var i GetCacheStatsRow
	err := row.Scan(
		&i.ArtistsCount,
		&i.AlbumsCount,
		&i.TracksCount,
		&i.PlaylistsCount,
	)
	return i, err
}

const getMultipleSpotifyAlbums = `-- name: GetMultipleSpotifyAlbums :many
SELECT id, name, album_type, release_date, release_date_precision, total_tracks, image_url, label, popularity, artist_ids, track_ids, cached_at FROM spotify_albums 
WHERE id = ANY($1::text[])
`

func (q *Queries) GetMultipleSpotifyAlbums(ctx context.Context, dollar_1 []string) ([]SpotifyAlbum, error) {
	rows, err := q.db.QueryContext(ctx, getMultipleSpotifyAlbums, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpotifyAlbum
	for rows.Next() {
		var i SpotifyAlbum
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AlbumType,
			&i.ReleaseDate,
			&i.ReleaseDatePrecision,
			&i.TotalTracks,
			&i.ImageUrl,
			&i.Label,
			&i.Popularity,
			pq.Array(&i.ArtistIds),
			pq.Array(&i.TrackIds),
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMultipleSpotifyArtists = `-- name: GetMultipleSpotifyArtists :many
SELECT id, name, image_url, popularity, followers_total, genres, cached_at FROM spotify_artists 
WHERE id = ANY($1::text[])
`

func (q *Queries) GetMultipleSpotifyArtists(ctx context.Context, dollar_1 []string) ([]SpotifyArtist, error) {
	rows, err := q.db.QueryContext(ctx, getMultipleSpotifyArtists, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpotifyArtist
	for rows.Next() {
		var i SpotifyArtist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Popularity,
			&i.FollowersTotal,
			pq.Array(&i.Genres),
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMultipleSpotifyPlaylists = `-- name: GetMultipleSpotifyPlaylists :many
SELECT id, name, description, owner_id, owner_display_name, public, collaborative, followers_total, total_tracks, image_url, track_ids, cached_at FROM spotify_playlists 
WHERE id = ANY($1::text[])
`

func (q *Queries) GetMultipleSpotifyPlaylists(ctx context.Context, dollar_1 []string) ([]SpotifyPlaylist, error) {
	rows, err := q.db.QueryContext(ctx, getMultipleSpotifyPlaylists, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpotifyPlaylist
	for rows.Next() {
		var i SpotifyPlaylist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.OwnerDisplayName,
			&i.Public,
			&i.Collaborative,
			&i.FollowersTotal,
			&i.TotalTracks,
			&i.ImageUrl,
			pq.Array(&i.TrackIds),
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMultipleSpotifyTracks = `-- name: GetMultipleSpotifyTracks :many
SELECT id, name, duration_ms, disc_number, track_number, popularity, explicit, is_local, album_id, artist_ids, cached_at FROM spotify_tracks 
WHERE id = ANY($1::text[])
`

// =============================================================================
// BATCH OPERATIONS
// =============================================================================
func (q *Queries) GetMultipleSpotifyTracks(ctx context.Context, dollar_1 []string) ([]SpotifyTrack, error) {
	rows, err := q.db.QueryContext(ctx, getMultipleSpotifyTracks, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpotifyTrack
	for rows.Next() {
		var i SpotifyTrack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationMs,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.Popularity,
			&i.Explicit,
			&i.IsLocal,
			&i.AlbumID,
			pq.Array(&i.ArtistIds),
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpotifyAlbum = `-- name: GetSpotifyAlbum :one
SELECT id, name, album_type, release_date, release_date_precision, total_tracks, image_url, label, popularity, artist_ids, track_ids, cached_at FROM spotify_albums WHERE id = $1
`

// =============================================================================
// ALBUM OPERATIONS
// =============================================================================
func (q *Queries) GetSpotifyAlbum(ctx context.Context, id string) (SpotifyAlbum, error) {
	row := q.db.QueryRowContext(ctx, getSpotifyAlbum, id)
	var i SpotifyAlbum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AlbumType,
		&i.ReleaseDate,
		&i.ReleaseDatePrecision,
		&i.TotalTracks,
		&i.ImageUrl,
		&i.Label,
		&i.Popularity,
		pq.Array(&i.ArtistIds),
		pq.Array(&i.TrackIds),
		&i.CachedAt,
	)
	return i, err
}

const getSpotifyArtist = `-- name: GetSpotifyArtist :one
SELECT id, name, image_url, popularity, followers_total, genres, cached_at FROM spotify_artists WHERE id = $1
`

// =============================================================================
// ARTIST OPERATIONS
// =============================================================================
func (q *Queries) GetSpotifyArtist(ctx context.Context, id string) (SpotifyArtist, error) {
	row := q.db.QueryRowContext(ctx, getSpotifyArtist, id)
	var i SpotifyArtist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Popularity,
		&i.FollowersTotal,
		pq.Array(&i.Genres),
		&i.CachedAt,
	)
	return i, err
}

const getSpotifyPlaylist = `-- name: GetSpotifyPlaylist :one

SELECT id, name, description, owner_id, owner_display_name, public, collaborative, followers_total, total_tracks, image_url, track_ids, cached_at FROM spotify_playlists WHERE id = $1
`

// =============================================================================
// PLAYLIST OPERATIONS
// =============================================================================
func (q *Queries) GetSpotifyPlaylist(ctx context.Context, id string) (SpotifyPlaylist, error) {
	row := q.db.QueryRowContext(ctx, getSpotifyPlaylist, id)
	var i SpotifyPlaylist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerDisplayName,
		&i.Public,
		&i.Collaborative,
		&i.FollowersTotal,
		&i.TotalTracks,
		&i.ImageUrl,
		pq.Array(&i.TrackIds),
		&i.CachedAt,
	)
	return i, err
}

const getSpotifyTrack = `-- name: GetSpotifyTrack :one
SELECT id, name, duration_ms, disc_number, track_number, popularity, explicit, is_local, album_id, artist_ids, cached_at FROM spotify_tracks WHERE id = $1
`

// =============================================================================
// TRACK OPERATIONS
// =============================================================================
func (q *Queries) GetSpotifyTrack(ctx context.Context, id string) (SpotifyTrack, error) {
	row := q.db.QueryRowContext(ctx, getSpotifyTrack, id)
	var i SpotifyTrack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationMs,
		&i.DiscNumber,
		&i.TrackNumber,
		&i.Popularity,
		&i.Explicit,
		&i.IsLocal,
		&i.AlbumID,
		pq.Array(&i.ArtistIds),
		&i.CachedAt,
	)
	return i, err
}

const upsertMultipleSpotifyAlbumsFromJSON = `-- name: UpsertMultipleSpotifyAlbumsFromJSON :exec
INSERT INTO spotify_albums (
    id,
    name,
    album_type,
    release_date,
    release_date_precision,
    total_tracks,
    image_url,
    label,
    popularity,
    artist_ids,
    track_ids,
    cached_at
)
SELECT 
    (album->>'id')::text,
    (album->>'name')::text,
    (album->>'album_type')::text,
    NULLIF(album->>'release_date', '')::date,
    (album->>'release_date_precision')::text,
    (album->>'total_tracks')::int,
    NULLIF(album->>'image_url','')::text,
    NULLIF(album->>'label', '')::text,
    (album->>'popularity')::int,
    ARRAY(SELECT jsonb_array_elements_text(album->'artist_ids'))::text[],
    ARRAY(SELECT jsonb_array_elements_text(album->'track_ids'))::text[],
    (album->>'cached_at')::timestamp
FROM jsonb_array_elements($1::jsonb) AS album
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    album_type = EXCLUDED.album_type,
    release_date = EXCLUDED.release_date,
    release_date_precision = EXCLUDED.release_date_precision,
    total_tracks = EXCLUDED.total_tracks,
    image_url = EXCLUDED.image_url,
    label = EXCLUDED.label,
    popularity = EXCLUDED.popularity,
    artist_ids = EXCLUDED.artist_ids,
    track_ids = EXCLUDED.track_ids,
    cached_at = EXCLUDED.cached_at
`

func (q *Queries) UpsertMultipleSpotifyAlbumsFromJSON(ctx context.Context, dollar_1 json.RawMessage) error {
	_, err := q.db.ExecContext(ctx, upsertMultipleSpotifyAlbumsFromJSON, dollar_1)
	return err
}

const upsertMultipleSpotifyArtistsFromJSON = `-- name: UpsertMultipleSpotifyArtistsFromJSON :exec
INSERT INTO spotify_artists (
    id,
    name,
    image_url,
    popularity,
    followers_total,
    genres,
    cached_at
)
SELECT 
    (artist->>'id')::text,
    (artist->>'name')::text,
    NULLIF(artist->>'image_url', '')::text,
    (artist->>'popularity')::int,
    (artist->>'followers_total')::int,
    -- Handle genres as either JSON array or comma-separated string
    -- If JSON array: extract each element as text array
    -- If string: split by comma (fallback for legacy data)
    CASE 
        WHEN jsonb_typeof(artist->'genres') = 'array' 
        THEN ARRAY(SELECT jsonb_array_elements_text(artist->'genres'))
        ELSE string_to_array(NULLIF(artist->>'genres', ''), ',')::text[]
    END,
    (artist->>'cached_at')::timestamp
FROM jsonb_array_elements($1::jsonb) AS artist
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    image_url = EXCLUDED.image_url,
    popularity = EXCLUDED.popularity,
    followers_total = EXCLUDED.followers_total,
    genres = EXCLUDED.genres,
    cached_at = EXCLUDED.cached_at
`

func (q *Queries) UpsertMultipleSpotifyArtistsFromJSON(ctx context.Context, dollar_1 json.RawMessage) error {
	_, err := q.db.ExecContext(ctx, upsertMultipleSpotifyArtistsFromJSON, dollar_1)
	return err
}

const upsertMultipleSpotifyPlaylistsFromJSON = `-- name: UpsertMultipleSpotifyPlaylistsFromJSON :exec
INSERT INTO spotify_playlists (
    id,
    name,
    description,
    owner_id,
    owner_display_name,
    public,
    collaborative,
    followers_total,
    total_tracks,
    image_url,
    track_ids,
    cached_at
)
SELECT 
    (playlist->>'id')::text,
    (playlist->>'name')::text,
    NULLIF(playlist->>'description', '')::text,
    (playlist->>'owner_id')::text,
    NULLIF(playlist->>'owner_display_name', '')::text,
    (playlist->>'public')::boolean,
    (playlist->>'collaborative')::boolean,
    (playlist->>'followers_total')::int,
    (playlist->>'total_tracks')::int,
    NULLIF(playlist->>'image_url', '')::text,
    ARRAY(SELECT jsonb_array_elements_text(playlist->'track_ids'))::text[],
    (playlist->>'cached_at')::timestamp
FROM jsonb_array_elements($1::jsonb) AS playlist
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    owner_id = EXCLUDED.owner_id,
    owner_display_name = EXCLUDED.owner_display_name,
    public = EXCLUDED.public,
    collaborative = EXCLUDED.collaborative,
    followers_total = EXCLUDED.followers_total,
    total_tracks = EXCLUDED.total_tracks,
    image_url = EXCLUDED.image_url,
    track_ids = EXCLUDED.track_ids,
    cached_at = EXCLUDED.cached_at
`

func (q *Queries) UpsertMultipleSpotifyPlaylistsFromJSON(ctx context.Context, dollar_1 json.RawMessage) error {
	_, err := q.db.ExecContext(ctx, upsertMultipleSpotifyPlaylistsFromJSON, dollar_1)
	return err
}

const upsertMultipleSpotifyTracksFromJSON = `-- name: UpsertMultipleSpotifyTracksFromJSON :exec
INSERT INTO spotify_tracks (
    id, name, album_id, duration_ms, disc_number, track_number,
    popularity, explicit, is_local, artist_ids, cached_at
)
SELECT 
    (track->>'id')::text,
    (track->>'name')::text,
    (track->>'album_id')::text,
    (track->>'duration_ms')::int,
    (track->>'disc_number')::int,
    (track->>'track_number')::int,
    (track->>'popularity')::int,
    (track->>'explicit')::boolean,
    (track->>'is_local')::boolean,
    ARRAY(SELECT jsonb_array_elements_text(track->'artist_ids'))::text[],
    (track->>'cached_at')::timestamp
FROM jsonb_array_elements($1::jsonb) AS track
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    album_id = EXCLUDED.album_id,
    duration_ms = EXCLUDED.duration_ms,
    disc_number = EXCLUDED.disc_number,
    track_number = EXCLUDED.track_number,
    popularity = EXCLUDED.popularity,
    explicit = EXCLUDED.explicit,
    is_local = EXCLUDED.is_local,
    artist_ids = EXCLUDED.artist_ids,
    cached_at = EXCLUDED.cached_at
`

func (q *Queries) UpsertMultipleSpotifyTracksFromJSON(ctx context.Context, dollar_1 json.RawMessage) error {
	_, err := q.db.ExecContext(ctx, upsertMultipleSpotifyTracksFromJSON, dollar_1)
	return err
}

const upsertSpotifyAlbum = `-- name: UpsertSpotifyAlbum :one
INSERT INTO spotify_albums (id, name, album_type, release_date, release_date_precision, total_tracks, image_url, label, popularity, track_ids, artist_ids, cached_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    album_type = EXCLUDED.album_type,
    release_date = EXCLUDED.release_date,
    release_date_precision = EXCLUDED.release_date_precision,
    total_tracks = EXCLUDED.total_tracks,
    image_url = EXCLUDED.image_url,
    label = EXCLUDED.label,
    popularity = EXCLUDED.popularity,
    track_ids = EXCLUDED.track_ids,
    artist_ids= EXCLUDED.artist_ids,
    cached_at = EXCLUDED.cached_at
RETURNING id, name, album_type, release_date, release_date_precision, total_tracks, image_url, label, popularity, artist_ids, track_ids, cached_at
`

type UpsertSpotifyAlbumParams struct {
	ID                   string
	Name                 string
	AlbumType            string
	ReleaseDate          sql.NullTime
	ReleaseDatePrecision string
	TotalTracks          int32
	ImageUrl             sql.NullString
	Label                sql.NullString
	Popularity           int32
	TrackIds             []string
	ArtistIds            []string
	CachedAt             time.Time
}

func (q *Queries) UpsertSpotifyAlbum(ctx context.Context, arg UpsertSpotifyAlbumParams) (SpotifyAlbum, error) {
	row := q.db.QueryRowContext(ctx, upsertSpotifyAlbum,
		arg.ID,
		arg.Name,
		arg.AlbumType,
		arg.ReleaseDate,
		arg.ReleaseDatePrecision,
		arg.TotalTracks,
		arg.ImageUrl,
		arg.Label,
		arg.Popularity,
		pq.Array(arg.TrackIds),
		pq.Array(arg.ArtistIds),
		arg.CachedAt,
	)
	var i SpotifyAlbum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AlbumType,
		&i.ReleaseDate,
		&i.ReleaseDatePrecision,
		&i.TotalTracks,
		&i.ImageUrl,
		&i.Label,
		&i.Popularity,
		pq.Array(&i.ArtistIds),
		pq.Array(&i.TrackIds),
		&i.CachedAt,
	)
	return i, err
}

const upsertSpotifyArtist = `-- name: UpsertSpotifyArtist :one
INSERT INTO spotify_artists (id, name, image_url, popularity, followers_total, genres, cached_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    image_url = EXCLUDED.image_url,
    popularity = EXCLUDED.popularity,
    followers_total = EXCLUDED.followers_total,
    genres = EXCLUDED.genres,
    cached_at = EXCLUDED.cached_at
RETURNING id, name, image_url, popularity, followers_total, genres, cached_at
`

type UpsertSpotifyArtistParams struct {
	ID             string
	Name           string
	ImageUrl       sql.NullString
	Popularity     sql.NullInt32
	FollowersTotal int32
	Genres         []string
	CachedAt       time.Time
}

func (q *Queries) UpsertSpotifyArtist(ctx context.Context, arg UpsertSpotifyArtistParams) (SpotifyArtist, error) {
	row := q.db.QueryRowContext(ctx, upsertSpotifyArtist,
		arg.ID,
		arg.Name,
		arg.ImageUrl,
		arg.Popularity,
		arg.FollowersTotal,
		pq.Array(arg.Genres),
		arg.CachedAt,
	)
	var i SpotifyArtist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Popularity,
		&i.FollowersTotal,
		pq.Array(&i.Genres),
		&i.CachedAt,
	)
	return i, err
}

const upsertSpotifyPlaylist = `-- name: UpsertSpotifyPlaylist :one
INSERT INTO spotify_playlists (id, name, description, owner_id, owner_display_name, public, collaborative, followers_total, total_tracks, image_url, track_ids, cached_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    owner_id = EXCLUDED.owner_id,
    owner_display_name = EXCLUDED.owner_display_name,
    public = EXCLUDED.public,
    collaborative = EXCLUDED.collaborative,
    followers_total = EXCLUDED.followers_total,
    total_tracks = EXCLUDED.total_tracks,
    image_url = EXCLUDED.image_url,
    track_ids = EXCLUDED.track_ids,
    cached_at = EXCLUDED.cached_at
RETURNING id, name, description, owner_id, owner_display_name, public, collaborative, followers_total, total_tracks, image_url, track_ids, cached_at
`

type UpsertSpotifyPlaylistParams struct {
	ID               string
	Name             string
	Description      sql.NullString
	OwnerID          string
	OwnerDisplayName sql.NullString
	Public           sql.NullBool
	Collaborative    sql.NullBool
	FollowersTotal   sql.NullInt32
	TotalTracks      sql.NullInt32
	ImageUrl         sql.NullString
	TrackIds         []string
	CachedAt         time.Time
}

func (q *Queries) UpsertSpotifyPlaylist(ctx context.Context, arg UpsertSpotifyPlaylistParams) (SpotifyPlaylist, error) {
	row := q.db.QueryRowContext(ctx, upsertSpotifyPlaylist,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.OwnerDisplayName,
		arg.Public,
		arg.Collaborative,
		arg.FollowersTotal,
		arg.TotalTracks,
		arg.ImageUrl,
		pq.Array(arg.TrackIds),
		arg.CachedAt,
	)
	var i SpotifyPlaylist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerDisplayName,
		&i.Public,
		&i.Collaborative,
		&i.FollowersTotal,
		&i.TotalTracks,
		&i.ImageUrl,
		pq.Array(&i.TrackIds),
		&i.CachedAt,
	)
	return i, err
}

const upsertSpotifyTrack = `-- name: UpsertSpotifyTrack :one
INSERT INTO spotify_tracks (id, name,  duration_ms, disc_number, track_number, popularity, explicit, is_local,album_id, artist_ids, cached_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    duration_ms = EXCLUDED.duration_ms,
    disc_number = EXCLUDED.disc_number,
    track_number = EXCLUDED.track_number,
    popularity = EXCLUDED.popularity,
    explicit = EXCLUDED.explicit,
    is_local = EXCLUDED.is_local,
    album_id = EXCLUDED.album_id,
    artist_ids = EXCLUDED.artist_ids,
    cached_at = EXCLUDED.cached_at
RETURNING id, name, duration_ms, disc_number, track_number, popularity, explicit, is_local, album_id, artist_ids, cached_at
`

type UpsertSpotifyTrackParams struct {
	ID          string
	Name        string
	DurationMs  int32
	DiscNumber  sql.NullInt32
	TrackNumber sql.NullInt32
	Popularity  sql.NullInt32
	Explicit    sql.NullBool
	IsLocal     sql.NullBool
	AlbumID     string
	ArtistIds   []string
	CachedAt    time.Time
}

func (q *Queries) UpsertSpotifyTrack(ctx context.Context, arg UpsertSpotifyTrackParams) (SpotifyTrack, error) {
	row := q.db.QueryRowContext(ctx, upsertSpotifyTrack,
		arg.ID,
		arg.Name,
		arg.DurationMs,
		arg.DiscNumber,
		arg.TrackNumber,
		arg.Popularity,
		arg.Explicit,
		arg.IsLocal,
		arg.AlbumID,
		pq.Array(arg.ArtistIds),
		arg.CachedAt,
	)
	var i SpotifyTrack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationMs,
		&i.DiscNumber,
		&i.TrackNumber,
		&i.Popularity,
		&i.Explicit,
		&i.IsLocal,
		&i.AlbumID,
		pq.Array(&i.ArtistIds),
		&i.CachedAt,
	)
	return i, err
}
